export { default as RnDSection } from "./RnDSection";
export { default as QualitySection } from "./QualitySection";
export { default as CloudSection } from "./CloudSection";
export { default as CaseStudiesSection } from "./CaseStudiesSection";
export { default as AwardsSection } from "./AwardsSection";
export { default as TestimonialsSection } from "./TestimonialsSection";
export { default as GallerySection } from "./GallerySection";
export { default as HiringSection } from "./HiringSection";
export { default as InternshipSection } from "./InternshipSection";
